imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: true
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
    dbal:
        driver: pdo_mysql
        host: 127.0.0.1
        port: null
        dbname: phpunit_test
        user: root
        password: null
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_unicode_ci
            engine: InnoDB